sudo: false
dist: trusty

language: ruby

cache:
  bundler: true

rvm:
  - 2.5.0

services:
  - postgresql
  - elasticsearch

addons:
  postgresql: '9.6'

notifications:
  email: false

before_install:
  # This is a workaround for a problem with a specific version of bundler and
  # rubygems
  - gem update --system

before_script:
  - RAILS_ENV=test bundle exec rails db:recreate
  - sleep 10

script:
  - bundle exec rspec --format documentation
