sudo: false
dist: trusty

language: ruby

cache:
  bundler: true

rvm:
  - 2.5.3

services:
  - postgresql
  - elasticsearch

addons:
  postgresql: '9.6'

notifications:
  email: false

before_install:
  - gem install bundler

before_script:
  - RAILS_ENV=test bundle exec rails db:recreate
  - ping_elasticsearch="curl localhost:9200"; while (! $ping_elasticsearch > /dev/null 2> /dev/null); do sleep 0.1; done

script:
  - bundle exec rspec --format documentation
